name: Build OCI Images

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the images
        run: |
          wget https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
          docker build --file pulp_ci/Containerfile --tag pulp/pulp-ci:latest .
          docker build --file pulp_fedora31/Containerfile --tag pulp/pulp-fedora31:latest .
          docker build --file pulp_galaxy_ng/Containerfile --tag pulp/pulp-galaxy-ng:latest .
