name: Build and publish OCI Images

on:
  push:
    branches:
      - latest
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      pulpcore:
        description: 'Release branch (e.g. 3.7)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.pulpcore }}
      - name: Download s6-overlay
        run: |
          wget https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
      - name: Build the images
        run: |
          version="${GITHUB_REF#refs/heads/}"
          if [ "$version" = "latest" ]; then
            docker build --file pulp_fedora31/Containerfile --tag pulp/pulp-fedora31:latest .
            docker build --file pulp_galaxy_ng/Containerfile --tag pulp/pulp-galaxy-ng:latest .
          fi
          docker build --file pulp_fedora31/Containerfile --tag pulp/pulp-fedora31:$version .
      - name: Docker login
        env:
          DOCKER_BOT_PASSWORD: ${{ secrets.DOCKER_BOT_PASSWORD }}
          DOCKER_BOT_USERNAME: ${{ secrets.DOCKER_BOT_USERNAME }}
        run: echo "$DOCKER_BOT_PASSWORD" | docker login -u "$DOCKER_BOT_USERNAME" --password-stdin docker.io
      - name: Push ci image to dockerhub
        run: |
          version="${GITHUB_REF#refs/heads/}"
          docker push docker.io/pulp/pulp-fedora31:$version
          if [ "$version" = "latest" ]; then
            docker push docker.io/pulp/pulp-galaxy-ng:latest
          fi
