name: pulp-oci-images CI

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:
  pull_request:
env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  single-process-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [pulp, galaxy]
        image_tag: [nightly, stable]
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install httpie and podman-compose
        run: |
          echo ::group::HTTPIE
          sudo apt-get update -yq
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends install httpie
          echo ::endgroup::
          echo "HTTPIE_CONFIG_DIR=$GITHUB_WORKSPACE/.ci/assets/httpie/" >> $GITHUB_ENV
          echo "APP=${{ matrix.app }}" >> $GITHUB_ENV
          export APP=${{ matrix.app }}
          # We set additional variables this way, rather than via the matrix, so that they
          # do not clutter the job names on the GHA webui.
          # Also so that we can use bash conditionals for undefined
          echo "IMAGE_TAG=${{ matrix.image_tag }}" >> $GITHUB_ENV
          if [ "${APP}" = "pulp" ]; then
            echo PIP_PKG_NAME_FOR_VERSION_STRING=pulpcore >> $GITHUB_ENV
          fi
          if [ "${APP}" = "galaxy" ]; then
            echo PIP_PKG_NAME_FOR_VERSION_STRING=galaxy-ng >> $GITHUB_ENV
          fi
          pip install podman-compose
        shell: bash
      - name: Build
        run: |
          podman version
          buildah version
          podman build --format docker --file images/Containerfile.core.base --tag pulp/base:latest .
          podman build --format docker --pull=false --file images/${APP}-minimal/$IMAGE_TAG/Containerfile.core --tag pulp/${APP}-minimal:$IMAGE_TAG .
          podman build --format docker --pull=false --file images/${APP}-minimal/$IMAGE_TAG/Containerfile.webserver --tag pulp/${APP}-web:$IMAGE_TAG .
          podman images -a
      - name: Compose up
        run: |
          cd images/compose
          sed -i "s/pulp-minimal:latest/${APP}-minimal:$IMAGE_TAG/g" docker-compose.yml
          sed -i "s/pulp-web:latest/${APP}-web:$IMAGE_TAG/g" docker-compose.yml
          sudo usermod -G root $(whoami)
          podman-compose up -d
          sleep 30
          for _ in $(seq 20)
          do
            sleep 3
            if curl --fail http://localhost:8080/pulp/api/v3/status/ > /dev/null 2>&1
            then
              break
            fi
          done
          curl --fail http://localhost:8080/pulp/api/v3/status/ | jq
        shell: bash
      - name: Test all components (pulp)
        if: matrix.app == 'pulp'
        run: |
          git clone --depth=1 https://github.com/pulp/pulp_ansible.git
          git clone --depth=1 https://github.com/pulp/pulp_container.git
          .ci/scripts/pulp_tests.sh
      - name: Test all components (galaxy)
        if: matrix.app == 'galaxy'
        run: |
          .ci/scripts/galaxy_ng-tests.sh
        shell: bash
        env:
          PY_COLORS: '1'
      - name: Github login
        if: github.event_name != 'pull_request'
        env:
          PULP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULP_GITHUB_USERNAME: ${{ github.actor }}
        run: echo "$PULP_GITHUB_TOKEN" | podman login -u "$PULP_GITHUB_USERNAME" --password-stdin ghcr.io
      - name: Push images to github
        if: github.event_name != 'pull_request'
        run: |
          podman tag pulp/base:latest ghcr.io/pulp/base:latest
          podman tag pulp/${APP}-minimal:$IMAGE_TAG ghcr.io/pulp/${APP}-minimal:$IMAGE_TAG
          podman tag pulp/${APP}-web:$IMAGE_TAG ghcr.io/pulp/${APP}-web:$IMAGE_TAG

          podman push ghcr.io/pulp/base:latest
          podman push ghcr.io/pulp/${APP}-minimal:$IMAGE_TAG
          podman push ghcr.io/pulp/${APP}-web:$IMAGE_TAG

          if [[ "$IMAGE_TAG" == "stable" ]]; then
            podman tag pulp/${APP}-minimal:stable ghcr.io/pulp/${APP}-minimal:latest
            podman tag pulp/${APP}-web:stable ghcr.io/pulp/${APP}-web:latest

            podman push ghcr.io/pulp/${APP}-minimal:latest
            podman push ghcr.io/pulp/${APP}-web:latest

            CURRENT_VERSION=$(podman run pulp/${APP}-minimal:stable bash -c "pip3 show ${PIP_PKG_NAME_FOR_VERSION_STRING} | sed -n -e 's/Version: //p'")
            echo $CURRENT_VERSION

            podman tag pulp/${APP}-minimal:stable ghcr.io/pulp/${APP}-minimal:$CURRENT_VERSION
            podman tag pulp/${APP}-web:stable ghcr.io/pulp/${APP}-web:$CURRENT_VERSION

            podman push ghcr.io/pulp/${APP}-minimal:$CURRENT_VERSION
            podman push ghcr.io/pulp/${APP}-web:$CURRENT_VERSION
          fi
          echo $CURRENT_VERSION
      - name: Docker login
        if: github.event_name != 'pull_request'
        env:
          DOCKER_BOT_PASSWORD: ${{ secrets.DOCKER_BOT_PASSWORD }}
          DOCKER_BOT_USERNAME: ${{ secrets.DOCKER_BOT_USERNAME }}
        run: echo "$DOCKER_BOT_PASSWORD" | podman login -u "$DOCKER_BOT_USERNAME" --password-stdin docker.io
      - name: Push images to dockerhub
        if: github.event_name != 'pull_request'
        run: |
          podman tag pulp/base:latest docker.io/pulp/base:latest
          podman tag pulp/${APP}-minimal:$IMAGE_TAG docker.io/pulp/${APP}-minimal:$IMAGE_TAG
          podman tag pulp/${APP}-web:$IMAGE_TAG docker.io/pulp/${APP}-web:$IMAGE_TAG

          podman push docker.io/pulp/base:latest
          podman push docker.io/pulp/${APP}-minimal:$IMAGE_TAG
          podman push docker.io/pulp/${APP}-web:$IMAGE_TAG

          if [[ "$IMAGE_TAG" == "stable" ]]; then
            podman tag pulp/${APP}-minimal:stable docker.io/pulp/${APP}-minimal:latest
            podman tag pulp/${APP}-web:stable docker.io/pulp/${APP}-web:latest

            podman push docker.io/pulp/${APP}-minimal:latest
            podman push docker.io/pulp/${APP}-web:latest

            CURRENT_VERSION=$(podman run pulp/${APP}-minimal:stable bash -c "pip3 show ${PIP_PKG_NAME_FOR_VERSION_STRING} | sed -n -e 's/Version: //p'")
            echo $CURRENT_VERSION

            podman tag pulp/${APP}-minimal:stable docker.io/pulp/${APP}-minimal:$CURRENT_VERSION
            podman tag pulp/${APP}-web:stable docker.io/pulp/${APP}-web:$CURRENT_VERSION

            podman push docker.io/pulp/${APP}-minimal:$CURRENT_VERSION
            podman push docker.io/pulp/${APP}-web:$CURRENT_VERSION
          fi
          echo $CURRENT_VERSION
      - name: Quay login
        if: github.event_name != 'pull_request'
        env:
          QUAY_BOT_PASSWORD: ${{ secrets.QUAY_BOT_PASSWORD }}
          QUAY_BOT_USERNAME: ${{ secrets.QUAY_BOT_USERNAME }}
        run: echo "$QUAY_BOT_PASSWORD" | podman login -u "$QUAY_BOT_USERNAME" --password-stdin quay.io
      - name: Push images to quay
        if: github.event_name != 'pull_request'
        run: |
          podman tag pulp/base:latest quay.io/pulp/base:latest
          podman tag pulp/${APP}-minimal:$IMAGE_TAG quay.io/pulp/${APP}-minimal:$IMAGE_TAG
          podman tag pulp/${APP}-web:$IMAGE_TAG quay.io/pulp/${APP}-web:$IMAGE_TAG

          podman push quay.io/pulp/base:latest
          podman push quay.io/pulp/${APP}-minimal:$IMAGE_TAG
          podman push quay.io/pulp/${APP}-web:$IMAGE_TAG

          if [[ "$IMAGE_TAG" == "stable" ]]; then
            podman tag pulp/${APP}-minimal:stable quay.io/pulp/${APP}-minimal:latest
            podman tag pulp/${APP}-web:stable quay.io/pulp/${APP}-web:latest

            podman push quay.io/pulp/${APP}-minimal:latest
            podman push quay.io/pulp/${APP}-web:latest

            CURRENT_VERSION=$(podman run pulp/${APP}-minimal:stable bash -c "pip3 show ${PIP_PKG_NAME_FOR_VERSION_STRING} | sed -n -e 's/Version: //p'")
            echo $CURRENT_VERSION

            podman tag pulp/${APP}-minimal:stable quay.io/pulp/${APP}-minimal:$CURRENT_VERSION
            podman tag pulp/${APP}-web:stable quay.io/pulp/${APP}-web:$CURRENT_VERSION

            podman push quay.io/pulp/${APP}-minimal:$CURRENT_VERSION
            podman push quay.io/pulp/${APP}-web:$CURRENT_VERSION
          fi
          echo $CURRENT_VERSION
      - name: Logs
        if: always()
        run: |
          podman ps -a
          podman images -a
          podman logs --tail=10000 compose_pulp_api_1
          podman logs --tail=10000 compose_pulp_content_1
          podman logs --tail=10000 compose_pulp_worker_1
          podman logs --tail=10000 compose_pulp_worker_2
          podman logs --tail=10000 compose_pulp_web_1
          VOLUME_PATH=$(podman volume inspect pulpdev | jq -r .[].Mountpoint)
          sudo ls -al $VOLUME_PATH
          sudo tree $VOLUME_PATH
          http --follow --timeout 30 --check-status --pretty format --print hb http://localhost:8080/pulp/api/v3/status/ || true
